### ISSUE TITLE
Handling requests without a reply

### ISSUE THREAD

**Issue by GlurG** [nats-io/node-nats#102]
I'm currently building a web application with a microservice architecture using Nats as the message broker. The service which is responsible for fetching data from database subscribes to a number of topics (e.g `fetch-username-by-email`, `update-user`, etc) so that other services can query the database. Now, if the database service would crash, the other services would "hang" if they tried to communicate with the crashed service (since they would not get any response). So, two questions regarding this:

1) Can the calling service get any information from Nats if the delivery of the message was successful or not? (According to http://nats.io/documentation/server/gnatsd-prune/ "dead" clients get pruned; maybe this information can be used to determine failed deliveries?)
2) Would you instead recommend implementing a timeout mechanism instead? (So the callback to `request` gets called regardless after a set amount of time)

**Comment by aricart** [comment]
NATS doesn't provide any delivery information or guarantees. You can try to use request reply with a timeout to notify the requestor that a reply was not received, but usually this is not going to be sufficient (the subscriber could have performed the task, and just died before sending the response). In node-nats, the timeout is implemented by creating a subscription or doing a request reply operation, and then passing the subscription id to the 'timeout' function provided by nats. A timeout will be performed if the specified number of messages are not received in the specified timeout.

With that said, coordination of a distributed transaction will require that you write to persistent state somewhere, and then also require that you make the requests idempotent, so that if the same request is re-initiated it doesn't have a bad side effect on your side.

What the prune documentation is trying to impart is that the subscription lists in NATS are auto pruned. This means that if there's no subscriber for a message or the subscriber disconnects, the server drops the message.

If you need message persistence see NATS streaming. However message persistence provided by NATS streaming is not a temporary queue or a per-client session queue but rather a message stream that can be played back by a subscriber, but perhaps it may be useful in the toolset for the problem you are trying to solve.

**Comment by MichaelErmer** [comment]
The GO implementation does automatically unsubscribe after 1 response and has a timeout options https://github.com/nats-io/go-nats/blob/master/nats.go#L1848

I think it would be a good solution to add a default value of 1 to the max options and add the option to set a timeout at the request time.

In my case I took the subscriptions to stack up to multiple million before the server itself crashed, to notice that one response does not unsub, which one would expect with a request function.
