### ISSUE TITLE
Request/Response Performance

### ISSUE THREAD

**Issue by StarpTech** [nats-io/node-nats#118]
Hi, I think there is much room for improvements. Could we use this ticket to talk about performance improvemets in general?

```
E:\Repositorys\node-nats>node benchmark\request_perf.js
Request Performance Test
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
12583 request-responses/sec
Avg roundtrip latency: 39 microseconds
```

**Request-responses/sec**: 12348 - 12583
**Payload**: 60 Bytes

Testcase - https://gist.github.com/StarpTech/a8032cb07ff17da691788bfda3df75af

**Comment by derekcollison** [comment]
Sure, feel free. But just so we are on the same page, we are sending a request, moving it over TCP to the server, processing it and sending it out, then the receiver sends a response, again over TCP and back through the server and returning to the requestor in 39 microseconds, not milliseconds. And remember, even with Node.js, you can parallelize both the request and the response so that they are not line blocking.

**Comment by StarpTech** [comment]
@derekcollison i'm aware of that and I won't look for performance issues on gnats :)

**Comment by derekcollison** [comment]
Point was even if you took Node.js and took out NATS and send a bunch of bytes over a socket like this, would you significantly beat 39 microseconds?

Requestor->Server->Responder->Server->Requestor

**Comment by StarpTech** [comment]
No its fast but I saw some rabbitmq rpc benchmarks which performs ~5000req/sec and I just thought nats can much more. I want to use this ticket to ask some question about the implementation.

**Comment by derekcollison** [comment]
I am sure we could do more if the responder was not same process. 

But we are still at 2.5x.
