### ISSUE TITLE
requestOne with timeout causes multiple responses

### ISSUE THREAD

**Issue by shaunpersad** [nats-io/node-nats#135]
Let's say I have one client who makes a requestOne call that exceeds the specified timeout, the callback will be called when the timeout is exceeded, as well as when the subscriber responds:

Client:
```
nats.requestOne('help', '', {}, 1000, function(response) {

    if(response instanceof NATS.NatsError && response.code === NATS.REQ_TIMEOUT) {
        console.log('Request for help timed out.');
        return;
    }
    console.log('Got a response for help: ', response);
});
```

Subscriber:
```
nats.subscribe('help', {queue:'help-service'}, function(request, replyTo) {
    
    setTimeout(function() {

        nats.publish(replyTo, 'I can help!');

    }, 10000);
});
```
Notice that the Client's timeout is 1s, but the Subscriber will take 10s to respond.

The client will output "Request for help timed out.", then output "Got a response for help: I can help!"

The expected output should just be "Request for help timed out."

**Comment by StarpTech** [comment]
@shaunpersad a timeout happens on client side. NATS don't know anything about it. You have to increase your timeout. It is possible to unsubscribe from the INBOX after it has reached the timeout but this is very special and a correct behaviour cannot be guaranteed. This can be implemented by yourself in just few lines. 

```js
var sid = nats.request('help', null, {}, 1000);
timeout(sid, function() {
  nats.unsubscribe(sid)
})

```

**Comment by aricart** [comment]
Actually this is a bug. The node client's `timeout` function (the normal way to do requests that timeout) doesn't auto-unsubscribe. Since `requestOne` is simply a convenience api setting the max number of expected responses, and calling `timeout`, it doesn't auto-unsubscribe either. The correct behaviour for both these api's is to unsubscribe on timeout.

**Comment by StarpTech** [comment]
@aricart but it can happen that the service is faster that the unsubscribtion of the client? so when the SID could not be found the message will be discarded right?

**Comment by aricart** [comment]
Not quite sure that I understand what you are saying. So let me try here:

When you unsubscribe, locally the node client will remove its subscription mapping. If a message doesn't have a matching subscription, it gets dropped. Since the node client is single threaded, when the unsubscribe is processed, the subscription is removed. If a new message is already in the buffer for the client during the unsubscribe, there's no matching subscription when the message processing happens. Similarly if the server happens to forward a message before processing the unsubscribe, it is will get sent to the client, but the client should drop it.

In this case, the subscription is still active on the client (and the server) until `unsubscribe` is called.

**Comment by ColinSullivan1** [comment]
Just to add a few thoughts on this - while the client may behave as expected as it is today, if the client does not unsubscribe, it leaves a subscription on the server for the lifetime of the connection.  With many requests, these subscription leaks will impact the server.  While this can be general problem in client design outside of request/reply, it should be addressed here as @aricart noted, for sake of the server under typical request/reply usage.

**Comment by aricart** [comment]
I have fixed this issue.

**Comment by StarpTech** [comment]
@aricart correct me if Im wrong but the subscription will be unsubscribed when:
1. normal subscribe on subject `test` with a timeout of `2000`
2. timeout occurs
3. unsubsribe occurs
4. **service will never gets messages**

**Comment by aricart** [comment]
Correct there will be no messages if it times out.

**Comment by StarpTech** [comment]
@aricart 

This behaviour will break lots of system because until version 0.7.14 the subject was still subscribed and messages could be received. This means that the client is resonsible to resubscribe on a timeout? If you use queue-groups this would mean that you assume that all subscribers are broken?

**Comment by aricart** [comment]
But that is not the correct intent is it?
If you subscribe expecting to timeout after a certain amount of time, you surely are not expecting the subscription to be active after the timeout when no messages were received. What is the meaning of a timeout on a subscriber? Even more basic, what is the meaning of a timeout?

A queue group is there to load-balance messages coming on a particular subject. While it is very likely that the 'replier' to a request is in a queue group, it doesn't sound right to make a queue group subscriber timeout on its subscription.

The only valid use of timeout is in a request/reply scenario from the perspective of the requestor. Where you expect responses to come back after a certain amount of time, and if not you need to be aware of the failure.

Our other client apis are handling the timeout by unsubscribing. Also note that the client is notified of the unsubscription if you specified a handler for `unsubscribe`.

**Comment by StarpTech** [comment]
@aricart I got it I misinterpret some points. The timout must be called explicit.
