### ISSUE TITLE
RFC: Separate typings from node-nats to node-nats-typings?

### ISSUE THREAD

**Issue by aricart** [nats-io/node-nats#157]
One issue with the current typings in node-nats and node-nats-streaming is that the projects are setup for Javascript. In most cases the typings definitions have been contributed. I am wondering if it would be a good thing to have a separate repos for the typings definitions. This would allow the repo to be properly setup and have at least minimal tests and samples.

Any comments from the community to this effect?

**Comment by tutman96** [comment]
I am not sure what you mean when you say "would allow the repo to be properly setup and have at least minimal tests". I am not familiar with the node-nats-streaming repo but I was under the impression that it used the node-nats module internally. I am not sure splitting out the typings into its own repo would help with anything.

**Comment by aricart** [comment]
It would keep each 'language' separate with their own examples etc.

**Comment by tutman96** [comment]
Ah, I see where you are coming from. Typescript, being an extension of javascript, allows me to simply copy and paste the javascript examples into my typescript project. The only difference comes with importing the nats module (`import nats = require('nats')` vs `var nats = require('nats')`) but that is a minimal difference. If I use typescript, I will get automatic type inferences because of the incorporated .d.ts file.

If this module were to have been written in typescript to begin with, it would work the same way. It gets a little more complicated with building/publishing but essentially the downloaded package from npm would contain a .js file and a .d.ts file.

I don't see a need for separate tests for the typings definitions.... could possible add a syntax check to the existing build procedure if you wanted to help catch some errors, but I don't think that is very necessary.

The only time where it would be beneficial to break the typings out into its own repo would be the case where the original package owner doesn't want to accept merges of typings into their own repo. This is where the DefinetlyTyped (@types) community comes in and provides alternative packages. I was able to get the owner of this package to accept my pull request of the initial .d.ts so that we didn't have to worry about the @types packages.
