### ISSUE TITLE
How to detect a slow consumer

### ISSUE THREAD

**Issue by StarpTech** [nats-io/node-nats#207]
Hi, according to https://github.com/nats-io/nats-site/blob/master/content/documentation/server/gnatsd-slow-consumers.md#slow-consumers-identified-in-the-client 

> It is better to catch a slow consumer locally in the client rather than to allow the server to detect this condition. This example demonstrates how to define and register an asynchronous error handler that will handle slow consumer errors.

How to archive this in Node.js?

When my applications run into a "slow consumer" condition no error is emitted. I only get a "REQ_TIMEOUT" on the producer side.

The next question is how can I recover from this state when I can't detect it? Thanks!

In https://github.com/nats-io/node-nats/issues/71 @derekcollison said that we can use an error callback which will let us know if the server dropped messages because the client was too slow. I couldn't find it https://github.com/nats-io/node-nats/blob/master/lib/nats.js#L132

**Comment by aricart** [comment]
@StarpTech The quick answer is  _you cannot_.  Multithreaded environments support this feature because the subscription buffers incoming messages while handlers and i/o tasks execute.

In node, user code is single threaded. When a data arrives and node sends an event dispatched to the event loop of the application. That event will trigger parsing of the data, if a message is found it is then dispatched to the subscription. The current inbound processing doesn't try to extract multiple messages as that would introduce an artificial latency. And while all that is going on, no other events can be processed.

If you are running into slow consumer problems, likely you need to scale your subscribers using queue groups so the load of the processing can be fanned out to multiple workers.

**Comment by StarpTech** [comment]
@aricart thanks for the explanation.

Theoretically: When I scale up my subscribers in combination with a queue-group it doesn't prevent me from a stale process. NATS will cut off the connection and the client will remain in a broken state without any chance to come back in a clear state.

According to nats documentation:
> ... When detected in the server, the server will disconnect the connection with the slow consumer to protect itself and the integrity of the messaging system.

so the best case is to restart the client in case of a socket "close" event and of course to scale up your consumers.

**Comment by aricart** [comment]
@StarpTech if the server disconnects you, your reconnect logic should trigger. Outbound messages in the pending queue should be published. On reconnect, the client will resubscribe. You will lose any messages that were in-flight when you were disconnected.

**Comment by StarpTech** [comment]
Yep, `disconnect` -> `reconnecting` -> `reconnect` event is fired, thanks!
