### ISSUE TITLE
Auto-unsubscribe request subscriptions?

### ISSUE THREAD

**Issue by ronag** [nats-io/node-nats#25]
Shouldn't requests subscriptions be auto-unsubscribed, i.e. `{max: 1}`? As it is now I believe a lot of people are leaving dangling subscriptions when using the request method.

If not I believe this needs to be more explicitly documented. If I hadn't read the code I wouldn't have realised as I don't believe even the examples unsubscribe.

**Comment by derekcollison** [comment]
I will take a look.. At first glance you may be right..

**Comment by derekcollison** [comment]
You are correct. I can't believe I did not catch this before. Thank you. Fix in progress. Will do a release shortly after.

**Comment by derekcollison** [comment]
Actually I correct myself. Since Node.js is not synchronous, nats.request() simply subscribes to an inbox for you but makes no assumptions on its own how many messages the client would want to receive or should be expected. The Subscriber Id (sid) will be returned and should be used to close the subscription as needed. Alternatively, if you know how many messages you want to receive at most,  you can pass an option block to indicate to nats.request() when to automatically unsubscribe. You can also pass other options like timeouts, etc.

E.g only want one response.

```js
nc.request('help', null, {'max':1}, function() {
  received += 1;
});
```

The test to make sure we don't leak.

https://github.com/nats-io/node-nats/blob/master/test/autounsub.js#L158

FYI I updated the docs to this to better reflect what is going on..

```js
/**
 * Publish a message with an implicit inbox listener as the reply. Message is optional.
 * This should be treated as a subscription. You can optionally indicate how many
 * messages you only want to receive using opt_options = {max:N}. Otherwise you
 * will need to unsubscribe to stop the message stream.
 * The Subscriber Id is returned.
 *
 * @param {String} subject
 * @param {String} opt_msg
 * @param {Object} opt_options
 * @param {Function} callback
 * @return {Mixed}
 * @api public
 */
```

**Comment by ronag** [comment]
Ok. That makes total sense. However, I believe this is one of those things a lot of people will intuitively get wrong. Would it maybe be a good idea to e.g add a requestSingle or request1 helper method?

**Comment by derekcollison** [comment]
Not with the true async mode of Node.js as the current client is written. Promises, etc will offer an opportunity to do so. 

Maybe update the README. I will do that..

**Comment by derekcollison** [comment]
See https://github.com/nats-io/node-nats/blob/master/README.md

**Comment by ajschlosser** [comment]
On a semi-related note, how does the server know when a client has died? Does it periodically ping clients to make sure that they are alive?

We had a few crashes over the past couple of days (unrelated to NATS), and it seems like our gnatsd server now has a lot of dangling subscriptions. Is there any way to clean that up (aside from restarting the server)?

**Comment by derekcollison** [comment]
You can monitor the server via the monitor port and tools like nats-top.

Both clients and the server will PING/PONG on a 2 minute (ish) interval.

Sounds like something may be leaking subscriptions, once a client connection is deemed dead by the server, the server will reap all of those subscriptions. But of a client is still up and leaking them, you want to know which client. The monitoring endpoints will tell you who.

**Comment by ajschlosser** [comment]
Good to know. Thanks!
